### ISSUE TITLE
[BUG] Tests are failing

### ISSUE THREAD

**Issue by arielj** [arielj/jeopardixir#14]
The generator for the User schema added many tests that are not valid

**Comment by geetfun** [comment]
Can confirm that running `mix test` does not work.

Following error:

```
➜  jeopardixir git:(feature/add-github-actions) mix test                   
==> connection
could not compile dependency :connection, "mix compile" failed. You can recompile this dependency with "mix deps.compile connection", update it with "mix deps.update connection" or clean it with "mix deps.clean connection"
** (File.Error) could not make directory (with -p) "/home/geetfun/projects/jeopardixir/_build/test/lib/connection": no such file or directory
    (elixir 1.12.2) lib/file.ex:316: File.mkdir_p!/1
    (mix 1.12.2) lib/mix/project.ex:675: Mix.Project.build_structure/2
    (mix 1.12.2) lib/mix/tasks/compile.all.ex:34: Mix.Tasks.Compile.All.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/compile.ex:128: Mix.Tasks.Compile.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/tasks/deps.compile.ex:172: anonymous fn/2 in Mix.Tasks.Deps.Compile.do_mix/2
```
